# Generated by Django 5.0.3 on 2025-10-06 14:08

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestionsObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(help_text='CBT question')),
                ('option_a', models.CharField(blank=True, help_text='Option A (leave blank for theory)', max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, help_text='Option B (leave blank for theory)', max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, help_text='Option C (leave blank for theory)', max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, help_text='Option D (leave blank for theory)', max_length=200, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Correct option (leave blank for theory)', max_length=1, null=True)),
                ('explanation', ckeditor.fields.RichTextField(blank=True, help_text='AI-generated detailed explanation', null=True)),
                ('explanation_generated', models.BooleanField(default=False, help_text='Set True after the AI generates an explanation')),
                ('hint', ckeditor.fields.RichTextField(blank=True, help_text='AI-generated detailed hint', null=True)),
                ('hint_generated', models.BooleanField(default=False, help_text='Set True after the AI generates an hint')),
                ('year', models.CharField(help_text='Year of the examination', max_length=4, null=True)),
                ('body', models.CharField(help_text='Waec / Jamb?', max_length=4, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_questions', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='ObjGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score', max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique submission ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objective_grades', to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_grades', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obj_grades', to='main.pastquestionsobj')),
            ],
        ),
        migrations.CreateModel(
            name='PastQuestionsTheory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Theory question')),
                ('year', models.CharField(help_text='Year of the examination', max_length=4, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_questions', to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.ManyToManyField(blank=True, related_name='students', to='main.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TheoryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', ckeditor.fields.RichTextField(help_text='Theory question', null=True)),
                ('response', ckeditor.fields.RichTextField(help_text="Student's response", null=True)),
                ('note', ckeditor.fields.RichTextField(help_text='Note for Student', null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score Over 100', max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique submission ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to='main.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to='main.pastquestionstheory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='main.course')),
            ],
        ),
        migrations.AddField(
            model_name='pastquestionsobj',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='main.topic'),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
