# Generated by Django 5.0.3 on 2025-12-07 04:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestionstheory',
            name='course',
        ),
        migrations.RemoveField(
            model_name='theorygrade',
            name='question',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='theorygrade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='theorygrade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pastquestionsobj',
            name='body',
        ),
        migrations.RemoveField(
            model_name='pastquestionsobj',
            name='year',
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ObjGrade',
        ),
        migrations.DeleteModel(
            name='PastQuestionsTheory',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TheoryGrade',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
