# Generated by Django 5.0.3 on 2026-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cbtresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastquestionsobj',
            name='option_e',
            field=models.CharField(blank=True, help_text='Option E (leave blank for theory)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pastquestionsobj',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('E', 'Option E')], help_text='Correct option (leave blank for theory)', max_length=1, null=True),
        ),
    ]
