# Generated by Django 5.0.3 on 2026-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pastquestionsobj_option_e_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='external_url',
            field=models.URLField(blank=True, help_text='Public link to document (Google Drive link preferred). When provided, the topic will show the embedded document.', null=True),
        ),
    ]
