# Generated by Django 5.0.3 on 2026-02-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_topic_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('Botany', 'Botany'), ('Cell Biology & Genetics', 'Cell Biology & Genetics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Geosciences', 'Geosciences (Geology/Geophysics)'), ('Marine Biology/Fisheries', 'Marine Biology/Fisheries'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Zoology', 'Zoology'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
