# Generated by Django 5.0.3 on 2026-02-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Reason for flagging (e.g., wrong answer, unclear question, typo)')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='Mark as resolved after addressing the issue')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='main.pastquestionsobj')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
