# Generated by Django 5.0.3 on 2026-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_flaggedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cbtresult',
            name='score',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flaggedquestion',
            name='flagged_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
