# Generated by Django 5.0.3 on 2026-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cbtresult_date_taken_alter_cbtresult_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtresult',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cbtresult',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flaggedquestion',
            name='flagged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
